#ifndef TNT_APP_H
#define TNT_APP_H

#define CMD_LONGOTP_WORKINGDIRECTORY "working-directory="
#define CMD_LONGOTP_WORKINGDIRECTORY_LEN sizeof(CMD_LONGOTP_WORKINGDIRECTORY) - 1

#define CMD_VERSION "CMD_VERSION"
#define CMD_HELP "CMD_HELP"
#define CMD_LOAD "CMD_LOAD"
#define CMD_LIST "CMD_LIST"
#define CMD_STAT "CMD_STAT"
#define CMD_GRAPH "CMD_GRAPH"
#define CMD_MAKE "CMD_MAKE"

#endif